-- Generated structure for a user-owned Supabase project.
-- Run this before seed.sql in the Supabase SQL Editor.

begin;

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('live', 'upcoming', 'other')),
  sport text not null,
  team_a text not null,
  team_b text,
  score_a integer not null default 0,
  score_b integer not null default 0,
  league text,
  match_time text,
  match_date text,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.servers (
  id bigint generated by default as identity primary key,
  sport text not null,
  server_name text not null,
  server_url text not null,
  position integer not null default 0,
  updated_at timestamptz not null default now(),
  match_id bigint
);

create table if not exists public.dami_catalog_snapshots (
  snapshot_hash text primary key,
  provider text not null default 'dami',
  fetched_at timestamptz not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists matches_sport_status_idx
  on public.matches (sport, status, position);
create index if not exists servers_sport_position_idx
  on public.servers (sport, position);
create index if not exists servers_match_id_idx
  on public.servers (match_id);
create index if not exists dami_catalog_snapshots_fetched_at_idx
  on public.dami_catalog_snapshots (fetched_at desc);

alter table public.matches enable row level security;
alter table public.servers enable row level security;
alter table public.dami_catalog_snapshots enable row level security;

drop policy if exists "Public can read matches" on public.matches;
create policy "Public can read matches"
  on public.matches for select to anon, authenticated using (true);

drop policy if exists "Public can read servers" on public.servers;
create policy "Public can read servers"
  on public.servers for select to anon, authenticated using (true);

drop policy if exists "Public can read catalog snapshots" on public.dami_catalog_snapshots;
create policy "Public can read catalog snapshots"
  on public.dami_catalog_snapshots for select to anon, authenticated using (true);

grant select on public.matches, public.servers, public.dami_catalog_snapshots
  to anon, authenticated;
revoke insert, update, delete on public.matches, public.servers, public.dami_catalog_snapshots
  from anon, authenticated;

commit;
